20ns_1995_pretrain:
  dataset: '20ns_1995'
  save_name: 'model_pretrain.pkl'
  input_type: 'tfidf'
  batch_size:  256
  epochs: 2000
  hidden_num: 256
  emb_size: 50
  learning_rate: 5.e-3
  level_num: 3
  topic_nums: 50
  freeze_word: False
  vocab_num: 1995
  init_word_scale:
    - 0.0001 
    - 0.01 
    - 0.9 
    - 0.999 
  init_topic_scale:
    - 0.0001
    - 0.01 
    - 0.9 
    - 0.999 
  intersect_temp: 0.1
  volume_temp: 0.1
  r1: 1.0 
  r2: 0.5
  r3: 0.05 # weight of word box constraint
  w1: 3.0 # weight of L_{CO} (alpha)
  w2: 0.005 # weight of L_{HT} (beta)
  sample_size: 128

nyt_pretrain:
  dataset: 'nyt'
  save_name: 'model_pretrain.pkl'
  input_type: "tfidf"
  batch_size:  256
  epochs: 2000
  hidden_num: 256
  emb_size: 50
  learning_rate: 5.e-3
  level_num: 3
  topic_nums: 50
  freeze_word: False
  vocab_num: 8171
  init_word_scale:
    - 0.0001
    - 0.01
    - 0.9
    - 0.999
  init_topic_scale:
    - 0.0001
    - 0.01
    - 0.9
    - 0.999
  intersect_temp: 0.1
  volume_temp: 0.1
  r1: 1.0
  r2: 0.5
  r3: 0.05 # weight of word box constraint
  w1: 3.0 # weight of L_{CO} (alpha)
  w2: 0.005 # weight of L_{HT} (beta)
  sample_size: 512

arxiv_pretrain:
  dataset: 'arxiv'
  save_name: 'model_pretrain.pkl'
  input_type: 'tfidf'
  batch_size:  512
  epochs: 500
  hidden_num: 256
  emb_size: 50
  learning_rate: 5.e-3
  level_num: 5
  topic_nums: 100
  freeze_word: False
  vocab_num: 11799
  init_word_scale:
    - 0.0001
    - 0.01
    - 0.9
    - 0.999
  init_topic_scale:
    - 0.0001
    - 0.01
    - 0.9
    - 0.999
  intersect_temp: 0.1
  volume_temp: 0.1
  r1: 1.0 
  r2: 0.5
  r3: 0.05 # weight of word box constraint
  w1: 3.0 # weight of L_{CO} (alpha)
  w2: 0.005 # weight of L_{HT} (beta)
  sample_size: 1024

20ns_1995:
  dataset: '20ns_1995'
  save_name: 'model.pkl'
  input_type: 'tfidf'
  batch_size:  256
  epochs: 2000
  hidden_num: 256
  emb_size: 50
  learning_rate: 5.e-3
  level_num: 3
  topic_nums: 50
  freeze_word: False
  vocab_num: 1995
  init_word_scale:
    - 0.0001 
    - 0.01 
    - 0.9 
    - 0.999 
  init_topic_scale:
    - 0.0001
    - 0.01 
    - 0.9 
    - 0.999 
  intersect_temp: 0.1
  volume_temp: 0.1
  r1: 1.0 
  r2: 0.5
  r3: 0.05 # weight of word box constraint
  w1: 3.0 # weight of L_{CO} (alpha)
  w2: 0.005 # weight of L_{HT} (beta)
  sample_size: 128

nyt:
  dataset: 'nyt'
  save_name: 'model.pkl'
  input_type: "tfidf"
  batch_size:  256
  epochs: 2000
  hidden_num: 256
  emb_size: 50
  learning_rate: 5.e-3
  level_num: 3
  topic_nums: 50
  freeze_word: False
  vocab_num: 8171
  init_word_scale:
    - 0.0001
    - 0.01
    - 0.9
    - 0.999
  init_topic_scale:
    - 0.0001
    - 0.01
    - 0.9
    - 0.999
  intersect_temp: 0.1
  volume_temp: 0.1
  r1: 1.0
  r2: 0.5
  r3: 0.05 # weight of word box constraint
  w1: 3.0 # weight of L_{CO} (alpha)
  w2: 0.005 # weight of L_{HT} (beta)
  sample_size: 512

arxiv:
  dataset: 'arxiv'
  save_name: 'model.pkl'
  input_type: 'tfidf'
  batch_size:  512
  epochs: 500
  hidden_num: 256
  emb_size: 50
  learning_rate: 5.e-3
  level_num: 5
  topic_nums: 100
  freeze_word: False
  vocab_num: 11799
  init_word_scale:
    - 0.0001
    - 0.01
    - 0.9
    - 0.999
  init_topic_scale:
    - 0.0001
    - 0.01
    - 0.9
    - 0.999
  intersect_temp: 0.1
  volume_temp: 0.1
  r1: 1.0 
  r2: 0.5
  r3: 0.05 # weight of word box constraint
  w1: 3.0 # weight of L_{CO} (alpha)
  w2: 0.005 # weight of L_{HT} (beta)
  sample_size: 1024